# Generated by Django 4.1.5 on 2023-01-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='rack',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='-', max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookitem',
            name='place',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
