# Generated by Django 4.1.5 on 2023-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_bookitem_rack_alter_bookitem_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='place',
            field=models.CharField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10'), (11, '11'), (12, '12'), (13, '13'), (14, '14'), (15, '15'), (16, '16'), (17, '17'), (18, '18'), (19, '19'), (20, '20')], max_length=2),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('IN_WORK', 'IN_WORK'), ('SUCCESS', 'SUCCESS'), ('FAIL', 'FAIL')], default='IN_WORK', max_length=10),
        ),
    ]
