# Generated by Django 4.1.5 on 2023-01-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_bookitem_place_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookitem',
            name='place',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
